CREATE TABLE paciente (

 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 nome VARCHAR(100) NOT NULL,
 email VARCHAR(100) NOT NULL,
 telefone VARCHAR(20) NOT NULL,
 cpf VARCHAR(14) NOT NULL,

 logradouro VARCHAR(100),
 bairro VARCHAR(100),
 cep VARCHAR(20),
 cidade VARCHAR(100),
 uf VARCHAR(10),
 numero VARCHAR(20),
 complemento VARCHAR(100),

 ativo BOOLEAN

);