spring.datasource.url=jdbc:mysql://localhost:3306/vitalmed
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none

server.error.include-stacktrace=never
jwt.secret=minha-chave-secreta-super-grande-12345678455